### ISSUE TITLE
no linefeeds in README.md generated from docGen.py

### ISSUE THREAD

**Issue by cwhitty** [Spirent/Velocity-assets#6]
1) please observe the README.md in https://github.com/Spirent/Velocity-assets/tree/master/Drivers/TestedBySpirent/ri_lepton and note that linefeeds are not appearing properly. for example, this appears as one big line:

Description: This is a supported driver for the 1024 port multirate ColdFusion L1 switch Category: driver Class: TestedBySpirent

2) is ### a markdown that should format text? note in the same README.md we have the string ###getProperties - should that be formatted text?

**Comment by alexorr** [comment]
The linefeed issue was caused by a difference in how Github uses markdown compared to the editor I was using. Github requires spaces after markdown chars. Also fixed an issue in reading and writing unicode chars, so quotes and other chars added to description fields in iTest are handled properly now. 

The script can be found on our internal Gitlab in this repo 
https://git-ito.spirenteng.com/APT-Field/tools
in the project up_GitDocScript
